import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "./hooks/useContext";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Victor ⎯ Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ContextProvider>
        <body className={dmSans.className}>{children}</body>
      </ContextProvider>
    </html>
  );
}
